version: '3'

services: # 서비스 설정
  db: # 서비스 이름 설정
    image: mysql # 사용할 이미지 설정
    restart: always # 컨테이너가 종료되면 항상 재시작
    command: # 컨테이너가 시작될 때 실행할 명령어
      - --character-set-server=utf8mb4 # MySQL 서버의 인코딩 방식을 설정
      - --collation-server=utf8mb4_unicode_ci # MySQL 서버의 콜레이션을 설정 # 콜레이션이란? 데이터베이스에서 문자열을 비교하거나 정렬할 때 사용하는 규칙
    environment: # 컨테이너에서 사용할 환경 변수 설정
      MYSQL_ROOT_PASSWORD: "idontknow" # MySQL 루트 계정의 비밀번호 설정
      MYSQL_DATABASE: "cardb" # MySQL 데이터베이스 이름 설정
      MYSQL_USER: "anything" # MySQL 사용자 이름 설정
      MYSQL_PASSWORD: "any00@@" #  MySQL 사용자 비밀번호 설정
    ports: # 호스트와 컨테이너의 포트를 연결
      - "3306:3306" # 호스트의 3306 포트를 컨테이너의 3306 포트에 연결
    volumes:
      - car_db_data:/var/lib/mysql # car_db_data 볼륨을 /var/lib/mysql 디렉토리에 연결

volumes:
  car_db_data: # 볼륨 이름 설정
    name: car_db_data # 사용할 볼륨 이름 설정